/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java
    id("org.openjfx.javafxplugin") version "0.0.7"
    // Apply the application plugin to add support for building an application
    application

}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

sourceSets {
    main {
        java.srcDirs("DiagramTool/src")
    }
    test {
        java.srcDirs("DiagramTool/test")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:27.0.1-jre")
    testCompile("org.junit.jupiter:junit-jupiter-api:5.2.0")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:5.2.0")
    testRuntime("org.junit.platform:junit-platform-console:1.2.0")
    implementation("org.reflections:reflections:0.9.11")
    // Use JUnit test framework
    testImplementation("junit:junit:4.12")

}

buildscript {
    repositories {
        maven {
            setUrl("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath("org.openjfx:javafx-plugin:0.0.7")
    }
}
javafx {
    modules("javafx.controls", "javafx.fxml" , "javafx.base")
}


apply(plugin = "org.openjfx.javafxplugin")
application {
    // Define the main class for the application
    mainClassName = "diagram.ui.CanvasUI"
}

